export interface Reserva {
  idReserva: number;
  idCliente: number;
  nombreCliente: string;
  dniCliente?: string;
  idAuto: number;
  placa: string;
  marca: string;
  modelo: string;
  fechaInicio: string;
  horaInicio: string;
  fechaFin: string;
  horaFin: string;
  kilometrajeInicio?: number;
  kilometrajeFin?: number;
  subtotal: number;
  mora: number;
  costoReparaciones: number;
  total: number;
  estado: string;
  estadoEntrega: string;
  observacionesEntrega?: string;
  fechaHoraInicioReal?: string;
  fechaHoraFinReal?: string;
  fechaCreacion: string;
  usuarioCreacion?: string;
  fechaFinalizacion?: string;
  usuarioFinalizacion?: string;
}
